### ISSUE TITLE
Possible bug raised by Infer

### ISSUE THREAD

**Issue by brucedaniel** [haojianzong/JZDatepicker#1]
/Users/<redacted>/<redacted>/<redacted>/jzdatepicker/StickyHeaderFlowLayout.m:41: error: NULL_DEREFERENCE
   pointer layoutAttributes last assigned on line 40 could be null and is dereferenced by call to addObject: at line 41, column 9

for more info on infer:

http://www.wired.com/2015/06/facebooks-ai-tool-squashing-bugs-now-open/
http://fbinfer.com/

**Comment by haojianzong** [comment]
Can you provide more information? Do you encounter anything unusual in your use case?
