### ISSUE TITLE
When numberOfDays = 0 , I got Error

### ISSUE THREAD

**Issue by KralMurat** [haojianzong/JZDatepicker#2]
Hi,

I want to let you know that when I set numberOfDays = 0 (in some screens I need to show only 1 date), I got crash. The crash info is : 
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'toDate must be after fromDate'

This line in JZDatepicker.m causes the crash:
NSAssert([fromDate compare:toDate] == NSOrderedAscending, @"toDate must be after fromDate");

When I delete it, there's no problem.

**Comment by haojianzong** [comment]
Thanks, didn't think of that use case. Fixed in the newest commit.
